### PR TITLE
Merging bug fixed branch with master

### PR DESCRIPTION
**Pull request by shoaibkhan17**
- Update search algorithm and style
- Show available quantity in cart
- Latest deployment build
- Updated UML class diagram to reflect Milestone 3

### CODE REVIEW

**Comment by meetdigrajkar** [comment]
Reviewed and verified changes

**Comment by shoaibkhan17** [comment]
The UML diagram looks good

**Review by meetdigrajkar — COMMENTED** [review]
Reviewed and verified

**Review by abdillahinur — APPROVED** [review]
UML Diagram added represents models with respect to Milestone 3
Changes work as intended, good to merge into master

**Review by meetdigrajkar — APPROVED** [review]
Reviewed and verified changes

**Pull request merged**
